/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ggp_noob_demo_base_jni_type_IntArray */

#ifndef _Included_com_ggp_noob_demo_base_jni_type_IntArray
#define _Included_com_ggp_noob_demo_base_jni_type_IntArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ggp_noob_demo_base_jni_type_IntArray
 * Method:    sumArray
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_ggp_noob_demo_base_jni_type_IntArray_sumArray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
