/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ggp_noob_demo_base_jni_type_ObjectArray */

#ifndef _Included_com_ggp_noob_demo_base_jni_type_ObjectArray
#define _Included_com_ggp_noob_demo_base_jni_type_ObjectArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ggp_noob_demo_base_jni_type_ObjectArray
 * Method:    initInt2DArray
 * Signature: (I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_ggp_noob_demo_base_jni_type_ObjectArray_initInt2DArray
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
