/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ggp_noob_demo_base_jni_type_Prompt */

#ifndef _Included_com_ggp_noob_demo_base_jni_type_Prompt
#define _Included_com_ggp_noob_demo_base_jni_type_Prompt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ggp_noob_demo_base_jni_type_Prompt
 * Method:    getLine
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ggp_noob_demo_base_jni_type_Prompt_getLine
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
