/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ggp_noob_demo_base_jni_JniHelloWorld */

#ifndef _Included_com_ggp_noob_demo_base_jni_JniHelloWorld
#define _Included_com_ggp_noob_demo_base_jni_JniHelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ggp_noob_demo_base_jni_JniHelloWorld
 * Method:    sayHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ggp_noob_demo_base_jni_JniHelloWorld_sayHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
